name: Build and deploy Python project to Azure Function App - csv-test-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # cesta k tvému projektu, root repo
  PYTHON_VERSION: '3.12'               # verze Pythonu, kterou používáš

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ZIP jen se soubory potřebnými pro funkci
      - name: Zip artifact for deployment
        run: zip release.zip function_app.py host.json requirements.txt

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
            app-name: 'csv-test-1'
            slot-name: 'Production'
            package: release.zip
            publish-profile: ${{ secrets.my_secret }}
